#!/usr/bin/env bash
# check-drift.sh — report drift between the canonical `.claude/` sources and the
# distributed copies (plugin + codex). READ-ONLY: never writes/copies anything.
#
# `.claude/` is the SINGLE SOURCE OF TRUTH. `codex/dist/` is generated by
# `python3 codex/build.py`. `plugins/vfm-agent-company/` mirrors `.claude/` with a
# transformed hooks layout and must be kept in sync deliberately.
#
# Usage:  bash .claude/scripts/check-drift.sh
# Exit:   0 = in sync, 1 = drift found.

set -uo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SRC="$ROOT/.claude"
PLUG="$ROOT/plugins/vfm-agent-company"
DRIFT=0

md5f() { md5 -q "$1" 2>/dev/null || md5sum "$1" 2>/dev/null | cut -d' ' -f1; }

# dir pairs that are DIRECT mirrors (same relative path under each root)
DIRECT_DIRS=(core agents helpers extensions schema pdf agent-memory templates)

echo "──────────────────────────────────────────────"
echo " DRIFT CHECK — canonical: .claude/   vs   plugins/vfm-agent-company/"
echo "──────────────────────────────────────────────"

for d in "${DIRECT_DIRS[@]}"; do
  [ -d "$SRC/$d" ] || continue
  while IFS= read -r f; do
    rel="${f#$SRC/$d/}"
    case "$rel" in *.DS_Store) continue;; esac
    dst="$PLUG/$d/$rel"
    if [ ! -f "$dst" ]; then
      echo "  ✗ MISSING in plugin : $d/$rel"; DRIFT=1
    elif [ "$(md5f "$f")" != "$(md5f "$dst")" ]; then
      echo "  ✗ DIFFERS           : $d/$rel"; DRIFT=1
    fi
  done < <(find "$SRC/$d" -type f ! -name .DS_Store)
done

# hooks: .claude/hooks/*.sh  →  plugin hooks/scripts/*.sh
if [ -d "$SRC/hooks" ]; then
  for f in "$SRC/hooks"/*.sh; do
    [ -f "$f" ] || continue
    b="$(basename "$f")"
    dst="$PLUG/hooks/scripts/$b"
    if [ ! -f "$dst" ]; then
      echo "  ✗ MISSING in plugin : hooks/scripts/$b"; DRIFT=1
    elif [ "$(md5f "$f")" != "$(md5f "$dst")" ]; then
      echo "  ⚠ DIFFERS (hook)    : hooks/scripts/$b  (paths may differ by design — review)"; DRIFT=1
    fi
  done
fi

echo "──────────────────────────────────────────────"
if [ "$DRIFT" -eq 0 ]; then
  echo " ✓ In sync."
else
  echo " ✗ Drift found. To resync:"
  echo "     • codex : python3 codex/build.py   (auto)"
  echo "     • plugin: update plugins/vfm-agent-company/ from .claude/ (manual —"
  echo "               hook path resolution differs, do not blind-copy .sh files)"
fi
exit $DRIFT
