#!/usr/bin/env bash
# check-drift.sh — report drift between the canonical `.claude/` sources and the
# distributed copies (plugin + codex). READ-ONLY: never writes/copies anything.
#
# `.claude/` is the SINGLE SOURCE OF TRUTH. `codex/dist/` is generated by
# `python3 codex/build.py`. `plugins/vfm-agent-company/` mirrors `.claude/` with a
# transformed hooks layout and must be kept in sync deliberately.
#
# Usage:  bash .claude/scripts/check-drift.sh
# Exit:   0 = in sync, 1 = drift found.

set -uo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SRC="$ROOT/.claude"
PLUG="$ROOT/plugins/vfm-agent-company"
DRIFT=0

md5f() { md5 -q "$1" 2>/dev/null || md5sum "$1" 2>/dev/null | cut -d' ' -f1; }

# dir pairs that are DIRECT mirrors (same relative path under each root)
# NOTE: `skills` MUST be here — a skill that exists in only one copy is drift
# (this is how the claude-architect meta-skill sat mis-placed and undetected).
DIRECT_DIRS=(core agents skills helpers extensions schema pdf agent-memory templates)

# files that are build/OS artifacts, never source — ignored in both directions
skip_artifact() { case "$1" in *.DS_Store|*/__pycache__/*|*.pyc) return 0;; *) return 1;; esac; }

echo "──────────────────────────────────────────────"
echo " DRIFT CHECK — canonical: .claude/   vs   plugins/vfm-agent-company/"
echo "──────────────────────────────────────────────"

# Forward: every canonical file must exist + match in the plugin
for d in "${DIRECT_DIRS[@]}"; do
  [ -d "$SRC/$d" ] || continue
  while IFS= read -r f; do
    skip_artifact "$f" && continue
    rel="${f#$SRC/$d/}"
    dst="$PLUG/$d/$rel"
    if [ ! -f "$dst" ]; then
      echo "  ✗ MISSING in plugin : $d/$rel"; DRIFT=1
    elif [ "$(md5f "$f")" != "$(md5f "$dst")" ]; then
      echo "  ✗ DIFFERS           : $d/$rel"; DRIFT=1
    fi
  done < <(find "$SRC/$d" -type f)
done

# Reverse: files that exist ONLY in the plugin (never added to canonical) are
# drift too — this is the exact class that hid claude-architect. Canonical wins.
for d in "${DIRECT_DIRS[@]}"; do
  [ -d "$PLUG/$d" ] || continue
  while IFS= read -r f; do
    skip_artifact "$f" && continue
    rel="${f#$PLUG/$d/}"
    if [ ! -f "$SRC/$d/$rel" ]; then
      echo "  ✗ ORPHAN in plugin  : $d/$rel  (exists in plugin, missing from canonical .claude/)"; DRIFT=1
    fi
  done < <(find "$PLUG/$d" -type f)
done

# hooks: .claude/hooks/*.sh  →  plugin hooks/scripts/*.sh
if [ -d "$SRC/hooks" ]; then
  for f in "$SRC/hooks"/*.sh; do
    [ -f "$f" ] || continue
    b="$(basename "$f")"
    dst="$PLUG/hooks/scripts/$b"
    if [ ! -f "$dst" ]; then
      echo "  ✗ MISSING in plugin : hooks/scripts/$b"; DRIFT=1
    elif [ "$(md5f "$f")" != "$(md5f "$dst")" ]; then
      echo "  ⚠ DIFFERS (hook)    : hooks/scripts/$b  (paths may differ by design — review)"; DRIFT=1
    fi
  done
fi

# ── Reference integrity ─────────────────────────────────────────────────────
# The mirror check above only proves the two copies are IDENTICAL. It cannot see
# a reference that is broken in BOTH copies — e.g. an agent that says
# `Read helpers/x.md` for a file nobody ever wrote, or a `lazySkills:` entry
# naming a plugin instead of a skill. Those fail silently at runtime: the agent
# reads nothing and improvises. Check every pointer resolves, on each side.
REFTMP="$(mktemp)"
check_refs() {
  local base="$1" label="$2" f ref s
  for f in "$base"/core/*.md "$base"/agents/*.md; do
    [ -f "$f" ] || continue
    # a) helpers/<name>.md pointers
    for ref in $(grep -oE 'helpers/[a-z0-9._-]+\.md' "$f" 2>/dev/null | sort -u); do
      if [ ! -f "$base/$ref" ]; then
        echo "  ✗ DANGLING REF   ($label): ${f#$base/} → $ref"; echo x >>"$REFTMP"
      fi
    done
    # b) lazySkills: entries must resolve to a skill directory
    for s in $(awk '/^lazySkills:/{inb=1;next}
                    inb && /^[[:space:]]*-[[:space:]]/{sub(/^[[:space:]]*-[[:space:]]*/,"");print;next}
                    inb{exit}' "$f"); do
      case "$s" in *:*) continue;; esac   # plugin-qualified skill, not local
      if [ ! -d "$base/skills/$s" ]; then
        echo "  ✗ DANGLING SKILL ($label): ${f#$base/} lazySkills → $s"; echo x >>"$REFTMP"
      fi
    done
  done
}
check_refs "$SRC"  "canonical"
check_refs "$PLUG" "plugin"
if [ -s "$REFTMP" ]; then DRIFT=1; fi
rm -f "$REFTMP"

echo "──────────────────────────────────────────────"
if [ "$DRIFT" -eq 0 ]; then
  echo " ✓ In sync."
else
  echo " ✗ Drift found. To resync:"
  echo "     • codex : python3 codex/build.py   (auto)"
  echo "     • plugin: update plugins/vfm-agent-company/ from .claude/ (manual —"
  echo "               hook path resolution differs, do not blind-copy .sh files)"
fi
exit $DRIFT
